import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
@Component({selector:'app-home',imports:[RouterLink],template:`
<div class="page">
<section class="hero"><div class="container hero-inner"><div><span class="eyebrow">🇮🇳 Admissions Open 2026–27</span><h1>Build a <span>Successful</span><br><em>Career</em> with Quality Education</h1><p>At CSS Group of Institutions, we combine experienced faculty, modern learning spaces and career-focused guidance to help students turn ambition into achievement.</p><div class="actions"><a class="btn btn-primary" routerLink="/enquiry">Start Your Enquiry →</a><a class="btn btn-outline" routerLink="/courses">Explore Courses</a></div></div><div class="hero-card"><img class="hero-logo" src="assets/logo.png" alt="CSS Group of Institutions"><div class="trust"><div><strong>2023</strong><span>Established</span></div><div><strong>4+</strong><span>Core strengths</span></div><div><strong>100%</strong><span>Placement assistance</span></div></div></div></div></section>
<section class="section"><div class="container"><div class="section-head center"><span class="kicker">Why CSS Group</span><h2>Education designed for the real world.</h2><p>We focus on knowledge, practical exposure and confidence so every learner is ready for the next step.</p></div><div class="feature-grid"><div class="feature"><div class="icon">🎓</div><h3>Expert Faculty</h3><p>Learn with dedicated educators and industry-oriented guidance.</p></div><div class="feature"><div class="icon">🏫</div><h3>Modern Campus</h3><p>Smart classrooms and practical learning environments built for growth.</p></div><div class="feature"><div class="icon">🏆</div><h3>Placement Assistance</h3><p>Career support focused on interview readiness and opportunities.</p></div><div class="feature"><div class="icon">📈</div><h3>Personality Development</h3><p>Build communication, confidence and professional skills for tomorrow.</p></div></div></div></section>
<section class="section features"><div class="container"><div class="section-head"><span class="kicker">Popular Programs</span><h2>Choose the path that fits your ambition.</h2></div><div class="course-grid"><div class="course"><span class="course-tag">Technology</span><h3>Computer Science & IT</h3><p>Career-focused programs for students interested in software, computing and digital skills.</p><a routerLink="/courses">View programs →</a></div><div class="course"><span class="course-tag">Management</span><h3>BBA & MBA</h3><p>Develop business thinking, leadership, communication and management skills.</p><a routerLink="/courses">View programs →</a></div><div class="course"><span class="course-tag">Applications</span><h3>BCA & MCA</h3><p>Build a strong foundation in applications, programming and modern computing.</p><a routerLink="/courses">View programs →</a></div></div></div></section>
<section class="section"><div class="container"><div class="stats"><div class="stat"><b>4+</b><span>Key strengths</span></div><div class="stat"><b>2023</b><span>Established</span></div><div class="stat"><b>100%</b><span>Placement assistance</span></div><div class="stat"><b>24×7</b><span>Enquiry support</span></div></div></div></section>
<section class="band"><div class="container band-inner"><div><h2>Ready to build your future?</h2><p>Talk to our admissions team and find the right course for you.</p></div><a class="btn btn-gold" routerLink="/enquiry">Enquire Now ↗</a></div></section>
</div>`}) export class HomeComponent {}
